import { FurnitureCatalogItem } from '../types/room';

export const FURNITURE_CATALOG: FurnitureCatalogItem[] = [
  // Bedroom
  {
    catalogId: 'double_bed',
    name: 'King Couple Bed',
    category: 'bedroom',
    icon: '🛏️',
    description: 'Plush double bed with soft duvet and twin pillows.',
    defaultColor: '#FF6B8B',
    availableColors: ['#FF6B8B', '#6C4AB6', '#4A90E2', '#E8D5C4', '#2C3E50'],
    gridWidth: 3,
    gridDepth: 4,
    height: 1.1,
    interactionType: 'sleep',
  },
  {
    catalogId: 'nightstand',
    name: 'Cozy Nightstand',
    category: 'bedroom',
    icon: '🪵',
    description: 'Bedside wooden drawer table with brass handle.',
    defaultColor: '#D4A373',
    availableColors: ['#D4A373', '#FFFFFF', '#3D348B', '#582F0E'],
    gridWidth: 1,
    gridDepth: 1,
    height: 0.65,
  },
  {
    catalogId: 'wardrobe',
    name: 'Double Wardrobe',
    category: 'bedroom',
    icon: '🚪',
    description: 'Spacious couple wardrobe for all shared outfits.',
    defaultColor: '#E9D8A6',
    availableColors: ['#E9D8A6', '#FFFFFF', '#6C4AB6', '#343A40'],
    gridWidth: 2,
    gridDepth: 1,
    height: 2.2,
  },
  {
    catalogId: 'fluffy_rug',
    name: 'Romantic Heart Rug',
    category: 'bedroom',
    icon: '🧶',
    description: 'Soft high-pile rug that feels warm underfoot.',
    defaultColor: '#FFD1DC',
    availableColors: ['#FFD1DC', '#E0AAFF', '#BEE1E6', '#FFF1E6'],
    gridWidth: 3,
    gridDepth: 3,
    height: 0.05,
  },
  {
    catalogId: 'table_lamp',
    name: 'Bedside Glow Lamp',
    category: 'bedroom',
    icon: '🏮',
    description: 'Gentle warm shade lamp creating romantic atmosphere.',
    defaultColor: '#FFE5B4',
    availableColors: ['#FFE5B4', '#FFCCD5', '#D8B4E2', '#E2ECE9'],
    gridWidth: 1,
    gridDepth: 1,
    height: 0.6,
  },

  // Living Room
  {
    catalogId: 'plush_sofa',
    name: 'Couple Cuddle Sofa',
    category: 'living_room',
    icon: '🛋️',
    description: 'Deep cushioned 2-seater sofa designed for hugs.',
    defaultColor: '#8E7DBE',
    availableColors: ['#8E7DBE', '#FF758F', '#48CAE4', '#F4A261', '#2B2D42'],
    gridWidth: 3,
    gridDepth: 2,
    height: 0.9,
    interactionType: 'sit',
  },
  {
    catalogId: 'coffee_table',
    name: 'Minimal Coffee Table',
    category: 'living_room',
    icon: '☕',
    description: 'Low-profile table with space for mugs and books.',
    defaultColor: '#CDB4DB',
    availableColors: ['#CDB4DB', '#FFFFFF', '#DDA15E', '#1D3557'],
    gridWidth: 2,
    gridDepth: 1,
    height: 0.45,
  },
  {
    catalogId: 'smart_tv',
    name: 'Smart Co-Watch TV',
    category: 'living_room',
    icon: '📺',
    description: 'High-definition screen connected to Watch Party co-streaming.',
    defaultColor: '#212529',
    availableColors: ['#212529', '#343A40', '#6C757D'],
    gridWidth: 3,
    gridDepth: 1,
    height: 1.4,
    interactionType: 'watch_tv',
  },
  {
    catalogId: 'bookshelf',
    name: 'Scandinavian Shelf',
    category: 'living_room',
    icon: '📚',
    description: '3-tier wooden shelf with romance novels and decor.',
    defaultColor: '#BC6C25',
    availableColors: ['#BC6C25', '#FFFFFF', '#8338EC', '#2B2D42'],
    gridWidth: 2,
    gridDepth: 1,
    height: 1.8,
  },
  {
    catalogId: 'potted_plant',
    name: 'Lush Monstera Plant',
    category: 'living_room',
    icon: '🪴',
    description: 'Living tropical houseplant in handcrafted ceramic pot.',
    defaultColor: '#2D6A4F',
    availableColors: ['#2D6A4F', '#52B788', '#40916C'],
    gridWidth: 1,
    gridDepth: 1,
    height: 1.1,
  },
  {
    catalogId: 'floor_lamp',
    name: 'Arched Living Lamp',
    category: 'lighting',
    icon: '💡',
    description: 'Elegant golden arc floor lamp with warm glow.',
    defaultColor: '#E0A96D',
    availableColors: ['#E0A96D', '#2B2D42', '#FFB703'],
    gridWidth: 1,
    gridDepth: 1,
    height: 1.9,
  },

  // Romantic Decorations
  {
    catalogId: 'heart_pillow',
    name: 'Giant Heart Pillow',
    category: 'romantic_decor',
    icon: '💖',
    description: 'Velvety oversized heart pillow for cuddling.',
    defaultColor: '#FF1493',
    availableColors: ['#FF1493', '#FF69B4', '#E63946', '#9B5DE5'],
    gridWidth: 1,
    gridDepth: 1,
    height: 0.35,
    interactionType: 'hug_near',
  },
  {
    catalogId: 'couple_frame',
    name: 'Shared Memory Frame',
    category: 'romantic_decor',
    icon: '🖼️',
    description: 'Tabletop gilded frame displaying your favorite couple memory.',
    defaultColor: '#D4AF37',
    availableColors: ['#D4AF37', '#C0C0C0', '#FFFFFF', '#E63946'],
    gridWidth: 1,
    gridDepth: 1,
    height: 0.5,
    interactionType: 'photo',
  },
  {
    catalogId: 'teddy_bear',
    name: 'Cupid Teddy Bear',
    category: 'romantic_decor',
    icon: '🧸',
    description: 'Fluffy plush teddy bear holding a tiny felt heart.',
    defaultColor: '#9C6644',
    availableColors: ['#9C6644', '#E6CCB2', '#DDB892', '#FAEDCD'],
    gridWidth: 1,
    gridDepth: 1,
    height: 0.55,
    interactionType: 'hug_near',
  },
  {
    catalogId: 'fairy_lights',
    name: 'Twinkling Fairy Lights',
    category: 'romantic_decor',
    icon: '✨',
    description: 'Strand of 12 glowing warm fairy bulbs strung on the wall.',
    defaultColor: '#FFD700',
    availableColors: ['#FFD700', '#FFB6C1', '#B0E0E6'],
    gridWidth: 3,
    gridDepth: 1,
    height: 0.4,
  },
  {
    catalogId: 'rose_vase',
    name: 'Bouquet of Roses',
    category: 'romantic_decor',
    icon: '🌹',
    description: 'Fresh cut red and blush pink roses in crystal glass vase.',
    defaultColor: '#E63946',
    availableColors: ['#E63946', '#FF758F', '#FFFFFF', '#FFB703'],
    gridWidth: 1,
    gridDepth: 1,
    height: 0.55,
  },
  {
    catalogId: 'candle_cluster',
    name: 'Romantic Candle Trio',
    category: 'romantic_decor',
    icon: '🕯️',
    description: 'Three scented vanilla candles with flickering flame effects.',
    defaultColor: '#FFF1E6',
    availableColors: ['#FFF1E6', '#FDE2E4', '#E2ECE9'],
    gridWidth: 1,
    gridDepth: 1,
    height: 0.35,
  },
];

export const CATEGORY_LABELS: Record<string, { label: string; icon: string }> = {
  bedroom: { label: 'Bedroom', icon: '🛏️' },
  living_room: { label: 'Living Room', icon: '🛋️' },
  romantic_decor: { label: 'Romantic Decor', icon: '💖' },
  lighting: { label: 'Lighting', icon: '💡' },
};
