import { RoomTemplate } from '../types/room';

export const ROOM_TEMPLATES: RoomTemplate[] = [
  {
    id: 'cozy_bedroom',
    name: 'Cozy Bedroom',
    roomType: 'bedroom',
    description: 'A warm sanctuary designed for restful nights and morning cuddles.',
    icon: '🛏️',
    dimensions: { width: 6, depth: 6, height: 3.2 },
    wallColor: '#FDF0ED',
    floorMaterial: 'hardwood_oak',
    lightingTheme: 'warm_sunset',
    windowScenery: 'city_sunset',
    defaultObjects: [
      {
        catalogId: 'double_bed',
        position: { x: 0, y: 0, z: -1.2 },
        rotationY: 0,
        color: '#FF6B8B',
        interactionType: 'sleep',
      },
      {
        catalogId: 'nightstand',
        position: { x: -1.8, y: 0, z: -1.8 },
        rotationY: 0,
        color: '#D4A373',
      },
      {
        catalogId: 'table_lamp',
        position: { x: -1.8, y: 0.65, z: -1.8 },
        rotationY: 0,
        color: '#FFE5B4',
      },
      {
        catalogId: 'fluffy_rug',
        position: { x: 0, y: 0, z: 1.0 },
        rotationY: 0,
        color: '#FFD1DC',
      },
      {
        catalogId: 'heart_pillow',
        position: { x: -0.5, y: 0.6, z: -1.8 },
        rotationY: 0,
        color: '#FF1493',
      },
      {
        catalogId: 'fairy_lights',
        position: { x: 0, y: 2.4, z: -2.4 },
        rotationY: 0,
        color: '#FFD700',
      },
    ],
  },
  {
    id: 'romantic_living',
    name: 'Romantic Living Room',
    roomType: 'living_room',
    description: 'A cozy lounge for movie dates, warm tea, and sofa cuddles.',
    icon: '🛋️',
    dimensions: { width: 6.5, depth: 6.5, height: 3.2 },
    wallColor: '#F7EDF8',
    floorMaterial: 'hardwood_dark',
    lightingTheme: 'romantic_pink',
    windowScenery: 'mountain_stars',
    defaultObjects: [
      {
        catalogId: 'plush_sofa',
        position: { x: 0, y: 0, z: 0.8 },
        rotationY: Math.PI,
        color: '#8E7DBE',
        interactionType: 'sit',
      },
      {
        catalogId: 'coffee_table',
        position: { x: 0, y: 0, z: -0.4 },
        rotationY: 0,
        color: '#CDB4DB',
      },
      {
        catalogId: 'smart_tv',
        position: { x: 0, y: 0, z: -2.4 },
        rotationY: 0,
        color: '#212529',
        interactionType: 'watch_tv',
      },
      {
        catalogId: 'teddy_bear',
        position: { x: 0.9, y: 0.45, z: 0.7 },
        rotationY: -Math.PI / 4,
        color: '#9C6644',
      },
      {
        catalogId: 'potted_plant',
        position: { x: -2.2, y: 0, z: -2.2 },
        rotationY: 0,
        color: '#2D6A4F',
      },
      {
        catalogId: 'floor_lamp',
        position: { x: 2.2, y: 0, z: 1.2 },
        rotationY: -Math.PI / 3,
        color: '#E0A96D',
      },
    ],
  },
  {
    id: 'modern_apartment',
    name: 'Modern Apartment',
    roomType: 'apartment',
    description: 'Sleek contemporary loft with open views and chic aesthetics.',
    icon: '🏙️',
    dimensions: { width: 7, depth: 7, height: 3.4 },
    wallColor: '#ECEFF1',
    floorMaterial: 'marble_pink',
    lightingTheme: 'bright_daylight',
    windowScenery: 'city_sunset',
    defaultObjects: [
      {
        catalogId: 'plush_sofa',
        position: { x: -1.2, y: 0, z: 0.5 },
        rotationY: Math.PI / 2,
        color: '#2B2D42',
        interactionType: 'sit',
      },
      {
        catalogId: 'smart_tv',
        position: { x: 1.6, y: 0, z: 0.5 },
        rotationY: -Math.PI / 2,
        color: '#212529',
        interactionType: 'watch_tv',
      },
      {
        catalogId: 'bookshelf',
        position: { x: 0, y: 0, z: -2.8 },
        rotationY: 0,
        color: '#BC6C25',
      },
      {
        catalogId: 'potted_plant',
        position: { x: 2.4, y: 0, z: -2.4 },
        rotationY: 0,
        color: '#2D6A4F',
      },
      {
        catalogId: 'couple_frame',
        position: { x: -1.8, y: 0.8, z: -2.6 },
        rotationY: 0,
        color: '#D4AF37',
        interactionType: 'photo',
      },
    ],
  },
  {
    id: 'beach_house',
    name: 'Beach House Retreat',
    roomType: 'beach_house',
    description: 'Breezy coastal hideaway with calming ocean vibes and sunlight.',
    icon: '🏖️',
    dimensions: { width: 6.5, depth: 6.5, height: 3.2 },
    wallColor: '#E0F2FE',
    floorMaterial: 'pastel_tile',
    lightingTheme: 'bright_daylight',
    windowScenery: 'beach_ocean',
    defaultObjects: [
      {
        catalogId: 'double_bed',
        position: { x: 0, y: 0, z: -1.0 },
        rotationY: 0,
        color: '#48CAE4',
        interactionType: 'sleep',
      },
      {
        catalogId: 'fluffy_rug',
        position: { x: 0, y: 0, z: 1.2 },
        rotationY: 0,
        color: '#BEE1E6',
      },
      {
        catalogId: 'rose_vase',
        position: { x: 1.8, y: 0, z: -1.4 },
        rotationY: 0,
        color: '#E63946',
      },
      {
        catalogId: 'candle_cluster',
        position: { x: -1.8, y: 0, z: -1.4 },
        rotationY: 0,
        color: '#FFF1E6',
      },
    ],
  },
  {
    id: 'dream_room',
    name: 'Dream Couple Room',
    roomType: 'dream_room',
    description: 'A magical fantasy palace under the stars built solely for two.',
    icon: '✨',
    dimensions: { width: 7.5, depth: 7.5, height: 3.6 },
    wallColor: '#FCE7F3',
    floorMaterial: 'cozy_carpet',
    lightingTheme: 'midnight_stars',
    windowScenery: 'mountain_stars',
    defaultObjects: [
      {
        catalogId: 'double_bed',
        position: { x: -1.6, y: 0, z: -1.4 },
        rotationY: 0,
        color: '#EC4899',
        interactionType: 'sleep',
      },
      {
        catalogId: 'plush_sofa',
        position: { x: 1.6, y: 0, z: 0.4 },
        rotationY: -Math.PI / 2,
        color: '#A855F7',
        interactionType: 'sit',
      },
      {
        catalogId: 'smart_tv',
        position: { x: 1.6, y: 0, z: -2.2 },
        rotationY: 0,
        color: '#212529',
        interactionType: 'watch_tv',
      },
      {
        catalogId: 'fairy_lights',
        position: { x: 0, y: 2.8, z: -3.0 },
        rotationY: 0,
        color: '#FFD700',
      },
      {
        catalogId: 'heart_pillow',
        position: { x: -1.6, y: 0.6, z: -0.6 },
        rotationY: 0,
        color: '#FF1493',
      },
      {
        catalogId: 'couple_frame',
        position: { x: 0, y: 1.4, z: -3.0 },
        rotationY: 0,
        color: '#D4AF37',
        interactionType: 'photo',
      },
    ],
  },
];

export const FLOOR_COLORS: Record<string, number> = {
  hardwood_oak: 0xdec09a,
  hardwood_dark: 0x5a3d28,
  marble_pink: 0xf7e1d7,
  pastel_tile: 0xd8e2dc,
  cozy_carpet: 0xfceade,
};

export const LIGHTING_COLORS: Record<string, { ambient: number; ambientInt: number; dir: number; dirInt: number; point: number }> = {
  warm_sunset: { ambient: 0xfff0e6, ambientInt: 0.8, dir: 0xffaa66, dirInt: 0.9, point: 0xff9966 },
  romantic_pink: { ambient: 0xffe6f0, ambientInt: 0.85, dir: 0xffa6c9, dirInt: 0.8, point: 0xff6699 },
  cozy_candlelight: { ambient: 0xfff5e6, ambientInt: 0.65, dir: 0xffaa33, dirInt: 0.75, point: 0xff8800 },
  bright_daylight: { ambient: 0xffffff, ambientInt: 0.95, dir: 0xfffaed, dirInt: 0.9, point: 0xfff0cc },
  midnight_stars: { ambient: 0xe6e6fa, ambientInt: 0.6, dir: 0x8a2be2, dirInt: 0.65, point: 0xda70d6 },
};
