import { AvatarStickerDef } from '../types';

export const COUPLE_STICKERS: AvatarStickerDef[] = [
  {
    id: 'stk-hug',
    title: 'Tight Hug ❤️',
    category: 'Affection',
    description: 'Wrapped in your warm embrace forever',
    interaction: 'hug',
    expression: 'loving',
    badge: '🫂',
    bgGradient: ['#FFE5EC', '#FFB3C6'],
  },
  {
    id: 'stk-kiss',
    title: 'Sweet Kiss 💋',
    category: 'Affection',
    description: 'A romantic kiss just for you',
    interaction: 'kiss',
    expression: 'blushing',
    badge: '💋',
    bgGradient: ['#F3E8FF', '#D8B4FE'],
  },
  {
    id: 'stk-cuddle',
    title: 'Cuddle Time 🛋️',
    category: 'Cozy',
    description: 'Leaning on your shoulder watching our stars',
    interaction: 'cuddle',
    expression: 'happy',
    badge: '🥰',
    bgGradient: ['#E0F2FE', '#BAE6FD'],
  },
  {
    id: 'stk-hearts',
    title: 'Sending Flying Hearts 💕',
    category: 'Love',
    description: 'Blowing showers of love across the distance',
    interaction: 'flying_hearts',
    expression: 'excited',
    badge: '💖',
    bgGradient: ['#FFF1F2', '#FECDD3'],
  },
  {
    id: 'stk-missing',
    title: 'Missing You So Much 🥺',
    category: 'Feelings',
    description: 'Counting down the seconds until I hold you again',
    interaction: 'hug',
    expression: 'shy',
    badge: '🥺',
    bgGradient: ['#F1F5F9', '#CBD5E1'],
  },
  {
    id: 'stk-morning',
    title: 'Good Morning Sunshine ☀️',
    category: 'Daily',
    description: 'Wishing you the brightest day, my love!',
    interaction: 'wave',
    expression: 'excited',
    badge: '☀️',
    bgGradient: ['#FEF3C7', '#FDE68A'],
  },
  {
    id: 'stk-night',
    title: 'Good Night & Sweet Dreams 🌙',
    category: 'Daily',
    description: 'Sleeping beside you in our dream world',
    interaction: 'sleep_beside',
    expression: 'loving',
    badge: '🌙',
    bgGradient: ['#EDE9FE', '#DDD6FE'],
  },
  {
    id: 'stk-dance',
    title: 'Slow Dance With Me 💃',
    category: 'Fun',
    description: 'Lost in our melody together',
    interaction: 'dance',
    expression: 'laughing',
    badge: '✨',
    bgGradient: ['#FDF2F8', '#FBCFE8'],
  },
];
